/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ClusterFinder.GUI;

/**
 *
 * @author MattChiappa
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        kMeans = new javax.swing.JButton();
        isodata = new javax.swing.JButton();
        dropdownPanel = new javax.swing.JPanel();
        algorithm = new javax.swing.JLabel();
        dropDown = new javax.swing.JComboBox();
        plotParam = new javax.swing.JPanel();
        plotLabel = new javax.swing.JLabel();
        graphPanel = new javax.swing.JPanel();
        paramPanel = new javax.swing.JPanel();
        parameters = new javax.swing.JLabel();
        on = new javax.swing.JLabel();
        oc = new javax.swing.JLabel();
        os = new javax.swing.JLabel();
        k = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        iLabel = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        help = new javax.swing.JButton();
        onText = new javax.swing.JTextField();
        ocText = new javax.swing.JTextField();
        osText = new javax.swing.JTextField();
        kText = new javax.swing.JTextField();
        lText = new javax.swing.JTextField();
        iText = new javax.swing.JTextField();
        minText = new javax.swing.JTextField();
        radioPanel = new javax.swing.JPanel();
        plot = new javax.swing.JRadioButton();
        scatter = new javax.swing.JRadioButton();
        plotType = new javax.swing.JLabel();
        stem = new javax.swing.JRadioButton();
        buttonPanel = new javax.swing.JPanel();
        plotButton = new javax.swing.JButton();
        calcButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        copyright = new javax.swing.JButton();
        filePanel = new javax.swing.JPanel();
        fileButton = new javax.swing.JButton();
        inputPanel = new javax.swing.JPanel();
        inputLabel = new javax.swing.JLabel();
        dimLabel = new javax.swing.JLabel();
        dimText = new javax.swing.JTextField();
        browse = new javax.swing.JButton();
        inputView = new javax.swing.JButton();
        fileOutput = new javax.swing.JPanel();
        fileOutputLabel = new javax.swing.JLabel();
        fileName = new javax.swing.JLabel();
        outputFileText = new javax.swing.JTextField();
        paramCheck = new javax.swing.JCheckBox();
        clusterCheck = new javax.swing.JCheckBox();
        coordCheck = new javax.swing.JCheckBox();
        groupCheck = new javax.swing.JCheckBox();
        screenShotCheck = new javax.swing.JCheckBox();
        save = new javax.swing.JButton();
        outputView = new javax.swing.JButton();
        outputPanel = new javax.swing.JPanel();
        outputLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        titlePanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                titlePanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        title.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Cluster Finder Using n-ISODATA/Kmeans Algorithm");

        author.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        author.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        author.setText("by Matthew Chiappa");

        kMeans.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kMeans.setText("K Means");
        kMeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kMeansActionPerformed(evt);
            }
        });

        isodata.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        isodata.setText("ISODATA");
        isodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isodataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(kMeans, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isodata, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kMeans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isodata, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(author)))
                .addGap(14, 14, 14))
        );

        dropdownPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        algorithm.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        algorithm.setText("Algorithm:");

        dropDown.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISODATA", "K Means", "Fuzzy K Means", " " }));
        dropDown.setToolTipText("");
        dropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dropdownPanelLayout = new javax.swing.GroupLayout(dropdownPanel);
        dropdownPanel.setLayout(dropdownPanelLayout);
        dropdownPanelLayout.setHorizontalGroup(
            dropdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropdownPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dropdownPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(algorithm)
                .addGap(45, 45, 45))
        );
        dropdownPanelLayout.setVerticalGroup(
            dropdownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropdownPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(algorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        plotParam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        plotLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plotLabel.setText("Plot:");

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        parameters.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        parameters.setText("Parameters:");

        on.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        on.setText("ON:");

        oc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        oc.setText("OC:");

        os.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        os.setText("OS:");

        k.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        k.setText("K:");

        l.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        l.setText("L:");

        iLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        iLabel.setText("I:");

        min.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        min.setText("MIN:");

        help.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        help.setText("Help");

        onText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        onText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        onText.setText("15");

        ocText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ocText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ocText.setText("10");
        ocText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocTextActionPerformed(evt);
            }
        });

        osText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        osText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        osText.setText("7");

        kText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kText.setText("4");
        kText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kTextActionPerformed(evt);
            }
        });

        lText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lText.setText("2");
        lText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lTextActionPerformed(evt);
            }
        });

        iText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        iText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iText.setText("10");
        iText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iTextActionPerformed(evt);
            }
        });

        minText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        minText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minText.setText("50");

        javax.swing.GroupLayout paramPanelLayout = new javax.swing.GroupLayout(paramPanel);
        paramPanel.setLayout(paramPanelLayout);
        paramPanelLayout.setHorizontalGroup(
            paramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paramPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paramPanelLayout.createSequentialGroup()
                        .addComponent(os)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(osText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paramPanelLayout.createSequentialGroup()
                        .addComponent(min)
                        .addGap(21, 21, 21)
                        .addGroup(paramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paramPanelLayout.createSequentialGroup()
                                .addComponent(help)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(paramPanelLayout.createSequentialGroup()
                        .addComponent(l)
                        .addGap(36, 36, 36)
                        .addComponent(lText))
                    .addGroup(paramPanelLayout.createSequentialGroup()
                        .addComponent(k)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paramPanelLayout.createSequentialGroup()
                        .addComponent(iLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(iText))
                    .addGroup(paramPanelLayout.createSequentialGroup()
                        .addComponent(oc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ocText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paramPanelLayout.createSequentialGroup()
                        .addComponent(parameters)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(paramPanelLayout.createSequentialGroup()
                        .addComponent(on)
                        .addGap(25, 25, 25)
                        .addComponent(onText)))
                .addContainerGap())
        );
        paramPanelLayout.setVerticalGroup(
            paramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paramPanelLayout.createSequentialGroup()
                .addComponent(parameters)
                .addGap(20, 20, 20)
                .addGroup(paramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(on)
                    .addComponent(onText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oc)
                    .addComponent(ocText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(osText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(os))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(k)
                    .addComponent(kText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l)
                    .addComponent(lText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min))
                .addGap(18, 18, 18)
                .addComponent(help)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout plotParamLayout = new javax.swing.GroupLayout(plotParam);
        plotParam.setLayout(plotParamLayout);
        plotParamLayout.setHorizontalGroup(
            plotParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotParamLayout.createSequentialGroup()
                .addGroup(plotParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plotParamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(plotLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(plotParamLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addComponent(paramPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        plotParamLayout.setVerticalGroup(
            plotParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotParamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plotParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plotParamLayout.createSequentialGroup()
                        .addComponent(plotLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(paramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        radioPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        plot.setText("Plot");
        plot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotActionPerformed(evt);
            }
        });

        scatter.setText("Scatter");

        plotType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plotType.setText("Plot Type:");

        stem.setText("Stem");
        stem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout radioPanelLayout = new javax.swing.GroupLayout(radioPanel);
        radioPanel.setLayout(radioPanelLayout);
        radioPanelLayout.setHorizontalGroup(
            radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plotType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scatter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        radioPanelLayout.setVerticalGroup(
            radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(plot)
                .addComponent(scatter)
                .addComponent(plotType)
                .addComponent(stem))
        );

        buttonPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        plotButton.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        plotButton.setText("Plot");

        calcButton.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        calcButton.setText("Calculate");

        resetButton.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        copyright.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        copyright.setText("Copyrights");

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addComponent(plotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plotButton)
                    .addComponent(calcButton)
                    .addComponent(resetButton)
                    .addComponent(copyright))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fileButton.setText("File Generator");

        inputPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        inputLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inputLabel.setText("Input(Text File):");

        dimLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dimLabel.setText("Dimensions:");

        dimText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dimText.setText("3");

        browse.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        browse.setText("Browse");

        inputView.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inputView.setText("View");
        inputView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addComponent(inputLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(dimLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dimText))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(browse, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputView, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addComponent(inputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dimLabel)
                    .addComponent(dimText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browse)
                    .addComponent(inputView))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        fileOutput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        fileOutputLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fileOutputLabel.setText("Output:");

        fileName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fileName.setText("File Name: ");

        outputFileText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        outputFileText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        outputFileText.setText("output");

        paramCheck.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        paramCheck.setText("Input Parameters");

        clusterCheck.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clusterCheck.setText("Number of Clusters");

        coordCheck.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        coordCheck.setText("Coordinates of Centers");

        groupCheck.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        groupCheck.setText("Cluster Groups");

        screenShotCheck.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        screenShotCheck.setText("Screenshot");

        save.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        save.setText("Save");

        outputView.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        outputView.setText("View");
        outputView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileOutputLayout = new javax.swing.GroupLayout(fileOutput);
        fileOutput.setLayout(fileOutputLayout);
        fileOutputLayout.setHorizontalGroup(
            fileOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileOutputLayout.createSequentialGroup()
                .addComponent(fileOutputLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(fileOutputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fileOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fileOutputLayout.createSequentialGroup()
                        .addComponent(fileName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputFileText))
                    .addGroup(fileOutputLayout.createSequentialGroup()
                        .addGroup(fileOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paramCheck)
                            .addComponent(clusterCheck)
                            .addComponent(coordCheck)
                            .addComponent(groupCheck)
                            .addComponent(screenShotCheck))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(fileOutputLayout.createSequentialGroup()
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fileOutputLayout.setVerticalGroup(
            fileOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileOutputLayout.createSequentialGroup()
                .addComponent(fileOutputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fileOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileName)
                    .addComponent(outputFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paramCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clusterCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coordCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(screenShotCheck)
                .addGap(12, 12, 12)
                .addGroup(fileOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(outputView))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout filePanelLayout = new javax.swing.GroupLayout(filePanel);
        filePanel.setLayout(filePanelLayout);
        filePanelLayout.setHorizontalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fileOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fileButton)
                .addGap(44, 44, 44))
        );
        filePanelLayout.setVerticalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        outputPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        outputLabel.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        outputLabel.setText("Output:");
        outputLabel.setToolTipText("");

        jScrollPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.background"));

        outputText.setColumns(20);
        outputText.setRows(5);
        jScrollPane1.setViewportView(outputText);

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addComponent(outputLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addComponent(outputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(radioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(69, 69, 69))
                            .addComponent(buttonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(plotParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(filePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropdownPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dropdownPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(plotParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kMeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kMeansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kMeansActionPerformed

    private void isodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isodataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isodataActionPerformed

    private void dropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropDownActionPerformed

    private void plotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plotActionPerformed

    private void stemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stemActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButtonActionPerformed

    private void ocTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocTextActionPerformed

    private void lTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lTextActionPerformed

    private void kTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kTextActionPerformed

    private void iTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iTextActionPerformed

    private void inputViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputViewActionPerformed

    private void outputViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputViewActionPerformed

    private void titlePanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_titlePanelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_titlePanelAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel algorithm;
    private javax.swing.JLabel author;
    private javax.swing.JButton browse;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton calcButton;
    private javax.swing.JCheckBox clusterCheck;
    private javax.swing.JCheckBox coordCheck;
    private javax.swing.JButton copyright;
    private javax.swing.JLabel dimLabel;
    private javax.swing.JTextField dimText;
    private javax.swing.JComboBox dropDown;
    private javax.swing.JPanel dropdownPanel;
    private javax.swing.JButton fileButton;
    private javax.swing.JLabel fileName;
    private javax.swing.JPanel fileOutput;
    private javax.swing.JLabel fileOutputLabel;
    private javax.swing.JPanel filePanel;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JCheckBox groupCheck;
    private javax.swing.JButton help;
    private javax.swing.JLabel iLabel;
    private javax.swing.JTextField iText;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JButton inputView;
    private javax.swing.JButton isodata;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel k;
    private javax.swing.JButton kMeans;
    private javax.swing.JTextField kText;
    private javax.swing.JLabel l;
    private javax.swing.JTextField lText;
    private javax.swing.JLabel min;
    private javax.swing.JTextField minText;
    private javax.swing.JLabel oc;
    private javax.swing.JTextField ocText;
    private javax.swing.JLabel on;
    private javax.swing.JTextField onText;
    private javax.swing.JLabel os;
    private javax.swing.JTextField osText;
    private javax.swing.JTextField outputFileText;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JTextArea outputText;
    private javax.swing.JButton outputView;
    private javax.swing.JCheckBox paramCheck;
    private javax.swing.JPanel paramPanel;
    private javax.swing.JLabel parameters;
    private javax.swing.JRadioButton plot;
    private javax.swing.JButton plotButton;
    private javax.swing.JLabel plotLabel;
    private javax.swing.JPanel plotParam;
    private javax.swing.JLabel plotType;
    private javax.swing.JPanel radioPanel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton save;
    private javax.swing.JRadioButton scatter;
    private javax.swing.JCheckBox screenShotCheck;
    private javax.swing.JRadioButton stem;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
